### ISSUE TITLE
New lines with matching fields will fail 

### ISSUE THREAD

**Issue by gnilekaw** [artsy/bearden#104]
Take the case of two CSVS:

**A**
```
organization_name,website,location,phone_number,email
"Foo's Bar", example.com, "Detroit, MI", , 
```

**B**
```
organization_name,website,location,phone_number,email
"Foo's Bar", example.com, , , foosbar@example.com
```

Both imports `A` and `B` are equally important. Unfortunately, `B` will fail because the row's import is saved in a transaction and `Foo's Bar` is invalid, since it already exists.

See https://github.com/artsy/bearden/pull/117 for a failing test.

**Comment by gnilekaw** [comment]
Is this being closed because it was fixed?

**Comment by jonallured** [comment]
Looks like this was mistakenly closed - reopening!

**Comment by madeleineb** [comment]
@gnilekaw Is work on this still ongoing?

**Comment by gnilekaw** [comment]
We talked about this briefly in the planning meeting. We're not currently working on it. We'd like to hold off fixing it unless there's a distinct problem from users.

**Comment by madeleineb** [comment]
Yes I'm fine with the stopgap we discussed at the planning meeting—there will be an error row in the errors CSV, and then we can just delete the offending duplicate field.

**Comment by jonallured** [comment]
I would like to hijack this issue and transform it to the following:

## During Import, ignore uniqueness validation errors on Organization Name

When we import a list and that list has a row with a matching website, we will fail the whole row if the Organization Name matches an existing name for the Organization. We do that because there is a uniqueness constraint on `OrganizationName`. What I propose is that we ignore that specific error during import - we simply throw out the organization name info and do not fail the whole row.

Given the scenario in the original post above, we pretend that this:

```
organization_name,website,location,phone_number,email
"Foo's Bar", example.com, , , foosbar@example.com
```

Is really this:

```
organization_name,website,location,phone_number,email
, example.com, , , foosbar@example.com
```

With that exception in place, I think we'll deal with the majority of errors around two lists having the same organization. It would satisfy the original case for this issue but wouldn't go too far and let junk data in.

I looked through the rest of the `Rankable`s and only `Website` also had the uniquness constraint, so I think this is as far as we have to take this exception.

Thoughts?

**Comment by gnilekaw** [comment]
Sounds good. Looks like there aren't really other uniqueness validators that will fail. https://github.com/artsy/bearden/search?utf8=%E2%9C%93&q=uniqueness&type= So we won't be in a situation where `organization_name` is just one of several fields that could fail in the same way.  I can imagine validators for email failing when there's no `@` but in that case the whole row _should_ fail!

**Comment by jonallured** [comment]
@gnilekaw cool, we're on the same page then! 👍 

@madeleineb if you're good with this, then I'll get started on it.

**Comment by jonallured** [comment]
After a couple conversations with @madeleineb and @gnilekaw, we have decided to just remove the uniqueness constraint on `OrganizationName`. None of the other Rankables have it - we just use the rank of the source of the data to determine a winner.

I'll get a commit in that does this.
