### ISSUE TITLE
Add Exception Notifications

### ISSUE THREAD

**Issue by jonallured** [artsy/bearden#163]
My favorite way to do this is with Honeybadger, but open to ideas. What I want to be able to get is a notification when an exception is raised, especially on production. @madeleineb has been testing on production and exceptions are being raised, but then not really persisted anywhere.

Plus, I'd like to know when they happen so that I can start investigating before she has to ask. 😉

**Comment by yuki24** [comment]
I'm jumping in for this conversation since I just noticed that there's [`rescue_from Exception` in Gravity](https://github.com/artsy/gravity/blob/c032946/app/controllers/application_controller.rb#L19), and wanted to let everyone know that [it's not encouraged by the Railsguide](http://guides.rubyonrails.org/action_controller_overview.html#rescue-from). Bearden doesn't have it right now, so it's 👍, and never add it.

That `rescue_from Exception` call would add a side-effect that silently makes any exception reporting services un-usable, so be careful when you have to edit error pages. just wanted to let you know about it and I'm totally 👍 for introducing a error reporting service.

**Comment by jonallured** [comment]
Yeah, I saw that post in Slack 😢 . Would be awesome if we had a Danger (Peril?) rule that looks for `Exception` in our Ruby code - you almost never want to be referencing that constant in a Rails app.

/cc @orta

**Comment by yuki24** [comment]
That's something rubocop might be able to do - I'll look into it to see if we can adda rule on this.

**Comment by jonallured** [comment]
Ok, I've configured this on both staging and production - HoneyBadger will notify in the appropriate Slack channel. If we end up wanting email notifications we can configure that too, but Slack seemed good enough for now.

**Comment by starsirius** [comment]
@yuki24 I think Rubocop already has a [rule](https://github.com/bbatsov/rubocop/blob/c8a3643080f4b28d716be147f10025f59b40f549/manual/cops_lint.md#lintrescueexception) for the blind rescue.
