### ISSUE TITLE
Don't set a default for `in_business` for organizations

### ISSUE THREAD

**Issue by madeleineb** [artsy/bearden#223]
`in_business` is defaulting to TRUE for records when the import did not include an `in_business` column (measured by count of in_business is null = 0). 

However, just because something is present in an import doesn't mean `in_business = TRUE`; without `in_business` being marked either TRUE or FALSE, the lack of an `in_business` entry means that the `in_business` status of that organization is unknown, and it should remain empty until we learn more about it.

**Comment by jonallured** [comment]
It's true, with [this commit](https://github.com/artsy/bearden/commit/60154d7c11dc1f83246814be6a881d1af0458cab#diff-f019497f997ab7b40a2ca463d93fcc89R3) I added the `in_business` column to `organizations` and set a default value of `true`. That means for all `Organization` records created thus far, we have no way of knowing if they are actually in business or if we don't know one way or the other. The thinking was that we'd assume they were in business until we were told otherwise and that seemed like a safe bet.

It would be simple enough to remove this default with another migration and then decide what to do with the current TRUE values (should they remain TRUE or be set to NULL?), but I wanted to just briefly push back on this and make sure we don't actually have a state column.

Dropping that default turns a boolean concept into a [trilean](https://en.wikipedia.org/wiki/Three-valued_logic) and maybe it'll end there, but would it be better to switch this column to a string that could represent more nuance? Maybe call it `state` as we do on `Sync` or `Import`. It could have values like this:

* `in_business` - we've seen signals that lead us to believe the Organization is in business
* `closed` - we've seen signals that lead us to believe the Organization is no longer in business
* `unknown` - the initial state which conveys that we don't currently know what the state of the business is

In addition to these values, you could imagine others, maybe something like `acquired` or `re-opened` or something else that I can't immediately think of. 😄 

My point is simply that with a string-type here we'd be able to convey more. I don't like NULLs, they're usually an indicator that you've missed something. If you think it's possible we'd want to represent something more sophisticated, I'd love to see us go in the direction of a state column.

Thoughts?

**Comment by madeleineb** [comment]
@jonallured super helpful explanation here!

This is good thinking—especially since "in_business" = FALSE can feel a bit like a double-negative way of expressing that something is `closed`. Calling it `state` and allowing it to exist as a string makes sense to me in this way. 

While `in business` `closed` and `unknown` make the most sense to me, and I can't off the top of my head think of others, that does also allow a more nuanced handling of the state in the future (`acquired` is a good one—we don't currently have data sets that would tell us this, but a human might know that two entities merged in the future).

Thanks for thinking of this 👍

**Comment by madeleineb** [comment]
Been thinking too about a clearer column name than `state`... `in_business_status`? May be a bit of a mouthful, but sounds like what it is.

**Comment by jonallured** [comment]
Cool, glad I brought it up then - @gnilekaw do you have any thoughts or concerns here? Do you have a preference for the name of this column?

@madeleineb what do you think about the existing TRUEs out there - should they be changed to `unknown`?

**Comment by madeleineb** [comment]
I think that they should be changed to `unknown`, _except_ for those with the source HumanOutsourcer. Those TRUEs should be `in_business`, as far as I understand, because someone checked their websites.

**Comment by gnilekaw** [comment]
I like `in_business = (open|closed|unknown)`.

**Comment by madeleineb** [comment]
For posterity, recording some "FAQs" on the behavior of `in_business`, which is time-sensitive information and thus not really the same as other rankable fields:

> Jon: the value of that field [`in_business`] on the organization will be whatever was last set
> Me: would an `unknown` override a `closed` or `open`?
> Jon: yes
> Me: would the lack of an `in_business` column in an import default to `unknown`?
> Jon: no

**Comment by jonallured** [comment]
Great point @madeleineb and I would just add that since `Organization` is audited by PaperTrail, all of these mutation are tracked should requirements change here.
